const actionTypes = {
    POETS: 'POETS',
    CATEGORIES:'CATEGORIES',
    HOME_POEMS: 'HOME_POEMS',
    ADD_TO_WISHLIST: 'ADD_TO_WISHLIST',
    SET_WISHLIST: 'SET_WISHLIST',
    SHOW_SEARCH: 'SHOW_SEARCH',
    HIDE_SEARCH: 'HIDE_SEARCH',
    REVIEW_STATUS: 'REVIEW_STATUS',


    LOGOUT: "LOGOUT",
    LOGIN: "LOGIN",
    LOADING_ON: "LOADING_ON",
    LOADING_OFF: "LOADING_OFF",
    GET_PROFILE: 'GET_PROFILE',

    MY_POEMS: 'MY_POEMS',
    ALL_POEMS: 'ALL_POEMS',
    LIKED_POEMS: 'LIKED_POEMS',
    NOTIFICATIONS: 'NOTIFICATIONS',
    TOGGLE_LIKE: 'TOGGLE_LIKE',
    REMOVE_POEM: 'REMOVE_POEM',
    EDIT_POEM: 'EDIT_POEM',

    ADD_COMMENT: 'ADD_COMMENT'
}

export default actionTypes