const actionTypes = {
    POETS: 'POETS',
    CATEGORIES:'CATEGORIES',
    HOME_POEMS: 'HOME_POEMS',
    ADD_TO_WISHLIST: 'ADD_TO_WISHLIST',
    SET_WISHLIST: 'SET_WISHLIST',
    SHOW_SEARCH: 'SHOW_SEARCH',
    HIDE_SEARCH: 'HIDE_SEARCH',
    REVIEW_STATUS: 'REVIEW_STATUS',

    LOGOUT: "LOGOUT",
    LOGIN: "LOGIN",
    LOADING_ON: "LOADING_ON",
    LOADING_OFF: "LOADING_OFF"
}

export default actionTypes